### ISSUE TITLE
Update device

### ISSUE THREAD

**Issue by gzsierra** [barracksiot/barracks-cli#64]
Hi,

Is there any options for update a single device?
Right now the only way I have figured out is by creating a new segment that match a single device and then `create` `publish` an update.

Nice feature would be creating an update for a device using something unique for him like `uint_id`

**Comment by saiimons** [comment]
Hi @gzsierra 

Targeting a single device is not a very common use case.
Our system is designed to handle groups or segments of devices, which size may be 1 device in size if needed, so you are doing the right thing 😄

**Comment by gzsierra** [comment]
Thanks for the reply!

I will continue on this path !
